In [168]:
import numpy as np
import cv2 as cv


In [169]:
#观测模型
def  观测(H,x):
    return H@x + np.random.normal(0,1/200)

In [170]:
#线性模型
def 数学模型(x,T):
    return T@x

In [171]:
class 卡尔曼:
    def __init__(self) -> None:
        pass
    def init_Parma(self,A,H,Q,R,P):
        #数学模型
        self.A=A#
     
        #观测
        self.H=H#
        # 协方差
        self.Q=Q#
        self.R=R#
        #P
        self.P=P
    def pridect(self,x,z):
           #先验预测
        self.x_pr = self.A@x 
        print(self.P)
        self.P = self.A@self.P@self.A.T + self.Q
        self.K = self.P@self.H.T/(self.H@self.P@self.H.T+self.R)
        self.x = self.x_pr + self.K@(z - self.H@self.x_pr)
        self.P = self.P - self.K@self.H@self.P
        return self.x
            
       


In [172]:
#世界生成；
from cv2 import normalize

po_x_r =0
v_x_r = 3
delt_t = 0.01
t_list = [i for i in range(0,100)]
t_list = np.array(t_list)
t_list =t_list*delt_t
x_list = []
for i in range(0,100):
    x_list.append(t_list[i]*3+np.random.normal(0,1/100))
x_list = np.array(x_list)
x_list

array([-1.51706192e-03,  3.96010709e-02,  4.11497350e-02,  9.05709473e-02,
        1.26834577e-01,  1.47720850e-01,  1.82889607e-01,  2.09984710e-01,
        2.42497304e-01,  2.54336596e-01,  2.98921520e-01,  3.35400236e-01,
        3.45134147e-01,  3.83269841e-01,  4.03667644e-01,  4.40480239e-01,
        4.83177001e-01,  4.95195235e-01,  5.41093102e-01,  5.76572456e-01,
        6.06614914e-01,  6.23147657e-01,  6.78058839e-01,  6.84862013e-01,
        7.25105491e-01,  7.54429482e-01,  7.83555573e-01,  8.13103768e-01,
        8.50662305e-01,  8.76085725e-01,  8.78551597e-01,  9.23798444e-01,
        9.56528470e-01,  9.76155458e-01,  1.02731133e+00,  1.05162756e+00,
        1.07166583e+00,  1.09463100e+00,  1.14675038e+00,  1.16085804e+00,
        1.19276422e+00,  1.24117680e+00,  1.25209104e+00,  1.29302011e+00,
        1.32146356e+00,  1.35414446e+00,  1.36819577e+00,  1.43082768e+00,
        1.43507407e+00,  1.45516788e+00,  1.50396961e+00,  1.52999565e+00,
        1.56220338e+00,  

In [173]:
#定义有关数学模型的变量
A = np.array([[1,1/100],[0,1]])
X =np.array([[0],[3]])

In [174]:
#定义有关观测模型的变量
H = np.array([[1,0]])
观测(H,[x_list[1],3])


array([0.03776145])

In [175]:
Q = np.array([ [1/10000,0 ],
               [0,1/10000] ])#数学模型协方差矩阵
R = np.array([[1/40000]])#观测协方差矩阵
P = np.array([[1,0],[0,1]])

In [176]:
kammer = 卡尔曼()
kammer.init_Parma(A,H,Q,R,P)

In [177]:
x = np.array([[x_list[0]],[3]])
x_kaer= []
x_观测= []
x_数学= []
for i in range(1,100):
    cc = 观测(H,[x_list[i],3])   #直接从传感器中取
    x = kammer.pridect(x,cc)
    x_数学.append(t_list[i]*3)
    x_观测.append(cc[0])
    x_kaer.append(x[0][0])
x_数学=np.array(x_数学)
x_观测=np.array(x_观测)
x_kaer=np.array(x_kaer)


[[1 0]
 [0 1]]
[[2.49993751e-05 2.49943763e-07]
 [2.49943763e-07 1.00000002e+00]]
[[2.25000438e-05 1.00000751e-03]
 [1.00000751e-03 6.00087011e-01]]
[[2.22528547e-05 7.69297132e-04]
 [7.69297132e-04 3.84756808e-01]]
[[2.18923172e-05 5.73910100e-04]
 [5.73910100e-04 2.78870185e-01]]
[[2.16444311e-05 4.51339042e-04]
 [4.51339042e-04 2.18263063e-01]]
[[2.14788240e-05 3.70986831e-04]
 [3.70986831e-04 1.79276340e-01]]
[[2.13626035e-05 3.14816701e-04]
 [3.14816701e-04 1.52128952e-01]]
[[2.12769216e-05 2.73438699e-04]
 [2.73438699e-04 1.32146452e-01]]
[[2.12112105e-05 2.41710100e-04]
 [2.41710100e-04 1.16826283e-01]]
[[2.11592360e-05 2.16614931e-04]
 [2.16614931e-04 1.04709436e-01]]
[[2.11171075e-05 1.96273893e-04]
 [1.96273893e-04 9.48881101e-02]]
[[2.10822759e-05 1.79456054e-04]
 [1.79456054e-04 8.67679102e-02]]
[[2.10530019e-05 1.65321620e-04]
 [1.65321620e-04 7.99433470e-02]]
[[2.10280583e-05 1.53278040e-04]
 [1.53278040e-04 7.41283163e-02]]
[[2.10065544e-05 1.42895261e-04]
 [1.42895261e-

In [178]:
cout = 0
for i in ((x_观测- x_list[1:])**2-(x_kaer- x_list[1:])**2>0):
    if(i):
        cout=cout+1
print(cout)

62


In [179]:
np.var(x_数学- x_list[1:])

8.28964332111793e-05

In [180]:

np.var((x_观测- x_list[1:]))


2.9447585534076646e-05

In [181]:
np.var((x_观测- x_list[1:]))/np.var((x_kaer- x_list[1:]))

1.217580443611558

In [182]:
(x_观测- x_list[1:]) - (x_kaer- x_list[1:])

array([ 2.31466040e-07, -2.69800247e-03,  3.54336369e-03,  2.15887288e-04,
        2.14810769e-04, -1.86891470e-04,  5.55240993e-04, -6.58342750e-04,
       -2.19264814e-03,  1.93863786e-03,  2.09636196e-03, -2.81306612e-03,
        2.52407928e-04, -1.84746241e-03, -6.84112522e-05,  4.09035382e-03,
       -1.40995777e-03,  2.95029401e-03,  4.69105108e-04, -9.65501167e-04,
       -2.34241701e-03,  5.51811387e-03, -3.56931318e-03,  7.99003380e-04,
       -1.03842503e-03,  3.08171427e-04,  9.29553995e-04,  2.24316477e-04,
        5.37629971e-04, -6.49637435e-03,  2.12688050e-03,  1.44454847e-03,
       -2.42628451e-03,  4.54408926e-03, -1.85026339e-03, -2.27182620e-03,
        2.24407436e-04,  3.64853833e-03, -3.15326454e-03,  1.42075990e-03,
        1.18501843e-03, -1.79039345e-03,  4.10295977e-04,  2.12006667e-03,
       -2.36683367e-03, -7.02387581e-04,  4.07592488e-03, -1.53916573e-03,
       -2.04226486e-03,  2.57988210e-03, -1.18250826e-03, -1.03300335e-03,
       -1.68220874e-03,  