In [753]:
import numpy as np
import cv2 as cv


In [754]:
#观测模型
def  观测(H,x):
    return H@x + np.random.normal(0,1/20)

In [755]:
#线性模型
def 数学模型(x,T):
    return T@x

In [756]:
class 卡尔曼:
    def __init__(self) -> None:
        pass
    def init_Parma(self,A,H,Q,R,P):
        #数学模型
        self.A=A
     
        #观测
        self.H=H
        # 协方差
        self.Q=Q
        self.R=R
        #P
        self.P=P
        
     
    def pridect(self,x,z):
           #先验预测
        self.x_pr = self.A@x 
        print(self.P)
        self.P = self.A@self.P@self.A.T + self.Q
        self.K = self.P@self.H.T/(self.H@self.P@self.H.T+self.R)
        self.x = self.x_pr + self.K@(z - self.H@self.x_pr)
        self.P = self.P - self.K@self.H@self.P
        return self.x
            
       


In [757]:
#世界生成；
from cv2 import normalize

po_x_r =0
v_x_r = 3
delt_t = 0.01
t_list = [i for i in range(0,100)]
t_list = np.array(t_list)
t_list =t_list*delt_t
x_list = []
for i in range(0,100):
    x_list.append(t_list[i]*3+np.random.normal(0,1/10))
x_list = np.array(x_list)


In [758]:
#定义有关数学模型的变量
A = np.array([[1,1/100],[0,1]])
X =np.array([[0],[3]])

In [759]:
#定义有关观测模型的变量
H = np.array([[1,0]])
观测(H,[x_list[1],3])


array([-0.00546957])

In [760]:
Q = np.array([ [1/100,0 ],
               [0,1/100] ])#数学模型协方差矩阵
R = np.array([[1/400]])#观测协方差矩阵
P = np.array([[1,0],[0,1]])

In [761]:
kammer = 卡尔曼()
kammer.init_Parma(A,H,Q,R,P)

In [762]:
x = np.array([[x_list[0]],[3]])
x_kaer= []
x_观测= []
x_数学= []
for i in range(1,100):
    cc = 观测(H,[x_list[i],3])
    x = kammer.pridect(x,cc)
    x_数学.append(t_list[i]*3)
    x_观测.append(cc[0])
    x_kaer.append(x[0][0])
x_数学=np.array(x_数学)
x_观测=np.array(x_观测)
x_kaer=np.array(x_kaer)


[[1 0]
 [0 1]]
[[2.49382777e-03 2.46889196e-05]
 [2.46889196e-05 1.00990124e+00]]
[[0.00208596 0.00167663]
 [0.00167663 1.01311176]]
[[0.00207543 0.00200528]
 [0.00200528 1.01364062]]
[[0.00207532 0.00206254]
 [0.00206254 1.01362352]]
[[0.00207535 0.00207209]
 [0.00207209 1.01351272]]
[[0.00207535 0.0020735 ]
 [0.0020735  1.01338805]]
[[0.00207535 0.00207352]
 [0.00207352 1.01326314]]
[[0.00207535 0.00207332]
 [0.00207332 1.01314025]]
[[0.00207535 0.00207308]
 [0.00207308 1.01301973]]
[[0.00207535 0.00207283]
 [0.00207283 1.0129016 ]]
[[0.00207535 0.00207259]
 [0.00207259 1.01278582]]
[[0.00207535 0.00207236]
 [0.00207236 1.01267234]]
[[0.00207535 0.00207213]
 [0.00207213 1.01256112]]
[[0.00207535 0.0020719 ]
 [0.0020719  1.01245212]]
[[0.00207535 0.00207168]
 [0.00207168 1.01234529]]
[[0.00207535 0.00207146]
 [0.00207146 1.01224058]]
[[0.00207535 0.00207125]
 [0.00207125 1.01213796]]
[[0.00207535 0.00207104]
 [0.00207104 1.01203738]]
[[0.00207535 0.00207084]
 [0.00207084 1.0119388 ]]


In [763]:
cout = 0
for i in ((x_观测- x_list[1:])**2-(x_kaer- x_list[1:])**2>0):
    if(i):
        cout=cout+1
print(cout)

48


In [764]:
np.var(x_数学- x_list[1:])

0.011549251370457904

In [765]:

np.var((x_观测- x_list[1:]))


0.00218812665566165

In [766]:
np.var((x_kaer- x_list[1:]))

0.002544157212238886

In [767]:
(x_观测- x_list[1:]) - (x_kaer- x_list[1:])

array([-0.00013443,  0.03333449, -0.03900002,  0.03281695, -0.00080192,
       -0.00961433, -0.01570577,  0.06945171, -0.05243258,  0.02076514,
        0.00696463, -0.0193052 , -0.02688562,  0.0287152 , -0.03658635,
        0.04522763, -0.01450904, -0.02571602, -0.02786722,  0.04280047,
        0.03004195,  0.0112384 , -0.05029489,  0.00061018, -0.01215051,
        0.04271675, -0.02525908, -0.00055464, -0.00816783,  0.02741184,
        0.00539491, -0.00168827,  0.00946933,  0.00494881, -0.04935046,
        0.0038875 ,  0.01562754,  0.04091009, -0.02601505,  0.01164263,
       -0.00363809, -0.03945137, -0.00551951,  0.00762154,  0.0040472 ,
        0.00568819,  0.00205956,  0.01475841, -0.01470905, -0.01661558,
        0.00900472, -0.01204397,  0.01616221,  0.00445626,  0.01007985,
       -0.00023362, -0.0322794 ,  0.01497138,  0.02658147, -0.00396664,
        0.03558087, -0.06273739,  0.01118587, -0.00030451, -0.01775163,
        0.00192235,  0.0156063 , -0.0135558 ,  0.00930783,  0.01